
<table id="list" class="table table-hover table-striped">
<thead>
    <tr>
        <th>Papel</th>
        <th>Permissões</th>
        <th>Papéis filhos</th>
        <th><a href="<?php echo $this->losUrl()->from('papel/add',[],true)?>" class="btn btn-sm btn-success pull-right"><?= $this->losIcon('glyphicon-plus') ?></a></th>
    </tr>
</thead>
<tbody>
    <?php foreach ($this->paginator as $entity):?>
        <tr class="linha">
            <td><?= $entity->getName() ?>
            </td>
            <td>
            <?php foreach ($entity->getPermissions() as $permissao): ?>
            <?php echo $permissao."<br>" ?>
            <?php endforeach;?>
            </td>
            <td>
            <?php foreach ($entity->getChildren() as $papelfilho): ?>
            <?php echo $papelfilho->getName()."<br>" ?>
            <?php endforeach;?>
            </td>            
            <td class="text-right">
                <a href="<?php echo $this->losUrl()->from('papel/edit',['id'=>$entity->getId()], true)?>" class="btn btn-xs btn-warning"><?= $this->losIcon('glyphicon-edit') ?></a>
                <a href="<?php echo $this->losUrl()->from('papel/delete',['id'=>$entity->getId()], true)?>" class="btn btn-xs btn-danger"><?= $this->losIcon('glyphicon-trash') ?></a>
            </td>
        </tr>
    <?php endforeach;?>
</tbody>
</table>

<?php if ($this->paginator->count() > 1):?>
<div class="row">
    <div class="col-xs-12 text-center"><?= $this->losPaginationControl($this->paginator,'Sliding',null,['query'=>$this->query]); ?></div>
</div>
<?php endif?>
